# general settings
name: DRP-BSRN_x2
model_type: SRModel
scale: 2
num_gpu: 0  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic/X4_sub
    dataroot_gt: /data/lpw/datasets/DF2K/DF2K_train_HR_sub
    dataroot_lq: /data/lpw/datasets/DF2K/DF2K_train_LR_bicubic/X2_sub
#    (for lmdb)
    # dataroot_gt: ./datasets/DF2K/DF2K_HR_sub.lmdb
    # dataroot_lq: ./datasets/DF2K/DF2K_train_LR_bicubic_X4_sub.lmdb
    # filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    # gt_size: 192
    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 50
    prefetch_mode: ~
# validation settings
  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Set5/GTmodx2
    dataroot_lq: datasets/Set5/LRbicx2
    io_backend:
      type: disk

# network structures
network_g:
  type: MyBSRN
  num_in_ch: 3
  num_feat: 64
  num_block: 8
  num_out_ch: 3
  upscale: 2
  conv: MyBSConvU2
  deploy_mode: false
  ESDB_mode: false # Distillation Conv2d;default=false,choose ESDB

# path
path:
  pretrain_network_g: models/DRP-BSRN_x2.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adan
    lr: !!float 5e-4
    betas: [0.98, 0.92, 0.99]
    weight_decay: 0
    foreach: true

  scheduler:
    type: MultiStepLR
    milestones: [200000,500000,800000]
    gamma: 0.5


  total_iter: 1000000
  # total_iter: 500000 
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
